version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 20
    reviewers:
      - furusax0621
    assignees:
      - furusax0621

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    reviewers:
      - furusax0621
    assignees:
      - furusax0621
