name: test

on:
  push:
  pull_request:
    branches: main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go:
          - "1.19"
          - "1.18"
    steps:
      - uses: actions/checkout@v3
      - name: setup go ${{ matrix.go }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
          cache: true
      - name: test
        run: go test -v -race ./...
