name: test

on:
  push:
    branches: main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go:
          - "1.20"
          - "1.18"
    steps:
      - uses: actions/checkout@v3
      - name: setup go ${{ matrix.go }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
      - name: test
        run: go test -v -race ./...
